[package]
name = "chrome-raw-websocket-automation"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
tokio-tungstenite = "0.23.1"
tungstenite = "0.23.0"
url = "2.5.2"
