[env]

CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
CARGO_MAKE_WORKSPACE_INCLUDE_MEMBERS = [
  "perseus_todo"
]

[tasks.run-perseus-todo]
category = "workspace"
command = "perseus"
args = ["serve", "-w"]
description = "Run perseus todo app"
