[package]
name = "quasi-prod-rust-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.4"
config = "0.14.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
temp-env = "0.3.6"
tokio = { version = "1.36.0", features = ["full"] }
