[package]
name = "tokio-n-tracing"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.21"
tokio = { version = "1.38.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter", "fmt"] }
