[package]
name = "one_hundred_kay"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
rand = "0.8.5"
reqwest = { version = "0.12.2", features = ["json"] }
tokio = { version = "1.37.0", features = ["full"] }
