version: '3.9'
services: 
  postgres:
    image: postgres
    restart: always
    environment: 
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=webservice_example

    ports: 
      - "5440:5432"
    volumes: 
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./sql:/docker-entrypoint-initdb.d/sql
    
  pgadmin-compose:
    image: dpage/pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "me@wtf.com"
      PGADMIN_DEFAULT_PASSWORD: "weetfeet"
    ports: 
      - "16543:80"
    depends_on: 
      - postgres
