[package]
name = "capn_proto_api_graphql"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
capnp = "0.19.0"
capnp-rpc = "0.19.0"
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["full"] }

[build-dependencies]
capnpc = "0.19.0"
