[package]
name = "macros_first_principles"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = { version = "1.0.86", features = ["nightly"] }
quote = "1.0.36"
syn = { version = "2.0.70", features = ["extra-traits", "full"] }
