[package]
name = "opentelemetry-from-docs"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = { version = "1.3.1", features = ["full"] }
rand = "0.8.5"
tokio = { version = "1.38.0", features = ["full"] }
