[package]
name = "tanti-srch"
version = "0.1.0"
edition = "2021"

[dependencies]
tantivy = { git = "https://github.com/quickwit-oss/tantivy", features = ["zstd", "zstd-compression"] }
tempfile = { version = "3.10.1", features = ["nightly"] }
