[package]
name = "thread-rave"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
indicatif = "0.17.8"
inquire = "0.7.5"
rand = "0.8.5"
rayon = "1.10.0"
tokio = { version = "1.39.0", features = ["full"] }
