[package]
name = "rust-crawl-pupp"
version = "0.1.0"
edition = "2021"

[dependencies]
chromiumoxide = { version = "0.5.7", features = ["tokio", "tokio-runtime"] }
futures = "0.3.30"
tokio = { version = "1.37.0", features = ["full"] }
